// Scenario of Fireworks launchers

var sequence0 = {
  "author": "Kei Yuasa",
  "created_date": "Dec 12, 2015",
  "body": [
		{ "pause": 160, "spots": [{"spot": 0, "color": "red", "velocity": 3}]},
		{ "pause": 120, "spots": [{"spot": 1, "color": "gold"}] },
		{ "pause": 100, "spots": [{"spot":2, "color": "aliceblue"}] },
		{ "pause": 80, "spots": [{"spot":3, "color": "yellowgreen"}] },
		{ "pause": 70, "spots": [{"spot":4, "color": "beige"}] },
		{ "pause": 60, "spots": [{"spot":5, "color": "bisque"}] },
		{ "pause": 50, "spots": [{"spot":6, "color": "lightsalmon"}] },
		{ "pause": 50, "spots": [{"spot":7, "color": "lightcoral"}] },
		{ "pause": 50, "spots": [{"spot":8, "color": "mediumpurple"}] },
		{ "pause": 50, "spots": [{"spot":9, "color": "turquoise"}] },
		{ "pause": 50, "spots": [{"spot":10, "color": "tomato"}] },
		{ "pause": 50, "spots": [{"spot":11, "color": "blue"}] },
		// one more
		{ "pause": 50, "spots": [{"spot": 0, "color": "red"}]},
		{ "pause": 50, "spots": [{"spot": 1, "color": "gold"}] },
		{ "pause": 50, "spots": [{"spot":2, "color": "aliceblue"}] },
		{ "pause": 50, "spots": [{"spot":3, "color": "yellowgreen"}] },
		{ "pause": 50, "spots": [{"spot":4, "color": "beige"}] },
		{ "pause": 50, "spots": [{"spot":5, "color": "bisque"}] },
		{ "pause": 50, "spots": [{"spot":6, "color": "lightsalmon"}] },
		{ "pause": 50, "spots": [{"spot":7, "color": "lightcoral"}] },
		{ "pause": 50, "spots": [{"spot":8, "color": "mediumpurple"}] },
		{ "pause": 50, "spots": [{"spot":9, "color": "turquoise"}] },
		{ "pause": 50, "spots": [{"spot":10, "color": "tomato"}] },
		{ "pause": 50, "spots": [{"spot":11, "color": "blue"}] },
		// 2 in 1 time
		{ "pause": 100, "spots": [{"spot":0, "color":"red"}, {"spot":6, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":1, "color":"red"}, {"spot":7, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":2, "color":"red"}, {"spot":8, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":3, "color":"red"}, {"spot":9, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":4, "color":"red"}, {"spot":10, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":5, "color":"red"}, {"spot":11, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":6, "color":"red"}, {"spot":0, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":7, "color":"red"}, {"spot":1, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":8, "color":"red"}, {"spot":2, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":9, "color":"red"}, {"spot":3, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":10, "color":"red"}, {"spot":4, color:"gold"}]},
		{ "pause": 40, "spots": [{"spot":11, "color":"red"}, {"spot":5, color:"gold"}]},
		//  Triple in 1
		{ "pause": 180, "spots": [{"spot":0, "color":"red"}, {"spot":4, color:"green"}, {"spot":8, color:"blue"}]},
		{ "pause": 40, "spots": [{"spot":1, "color":"red"}, {"spot":5, color:"green"}, {"spot":9, color:"blue"}]},
		{ "pause": 40, "spots": [{"spot":2, "color":"red"}, {"spot":6, color:"green"}, {"spot":10, color:"blue"}]},
		{ "pause": 40, "spots": [{"spot":3, "color":"red"}, {"spot":7, color:"green"}, {"spot":11, color:"blue"}]},
		
		// 1 round
		{ "pause": 80, "spots":[{"spot":11, "color":"#420202", "velocity": 5}]},
		{ "pause": 20, "spots":[{"spot":10, "color":"#421919", "velocity": 5}]}, 
		{ "pause": 20, "spots":[{"spot": 9, "color":"#423030", "velocity": 5}]}, 
		{ "pause": 20, "spots":[{"spot": 8, "color":"#424747", "velocity": 5}]},
		{ "pause": 20, "spots":[{"spot": 7, "color":"#425e5e", "velocity": 5}]}, 
		{ "pause": 20, "spots":[{"spot": 6, "color":"#427575", "velocity": 5}]}, 
		{ "pause": 20, "spots":[{"spot": 5, "color":"#428C8C", "velocity": 5}]},
		{ "pause": 20, "spots":[{"spot": 4, "color":"#42A3A3", "velocity": 5}]}, 
		{ "pause": 20, "spots":[{"spot": 3, "color":"#42baba", "velocity": 5}]}, 
		{ "pause": 20, "spots":[{"spot": 2, "color":"#42d1d1", "velocity": 5}]},
		{ "pause": 20, "spots":[{"spot": 1, "color":"#42e8e8", "velocity": 5}]},		                 		 
		{ "pause": 20, "spots":[{"spot": 0, "color":"#42ffff", "velocity": 5}]}, 		
		
		// quad
		{ "pause": 160, "spots": [{"spot": 0, "color":"blue"}, {"spot": 3, color:"red"}, {"spot": 6, color:"yellow"}, {"spot": 9, color:"green"}]},
		{ "pause":  60, "spots": [{"spot": 1, "color":"blue"}, {"spot": 4, color:"red"}, {"spot": 7, color:"yellow"}, {"spot":10, color:"green"}]},
		{ "pause":  60, "spots": [{"spot": 2, "color":"blue"}, {"spot": 5, color:"red"}, {"spot": 8, color:"yellow"}, {"spot":11, color:"green"}]},
		{ "pause":  40, "spots": [{"spot": 3, "color":"blue"}, {"spot": 6, color:"red"}, {"spot": 9, color:"yellow"}, {"spot": 0, color:"green"}]},
		{ "pause":  40, "spots": [{"spot": 4, "color":"blue"}, {"spot": 7, color:"red"}, {"spot":10, color:"yellow"}, {"spot": 1, color:"green"}]},
		{ "pause":  40, "spots": [{"spot": 5, "color":"blue"}, {"spot": 8, color:"red"}, {"spot":11, color:"yellow"}, {"spot": 2, color:"green"}]},
		{ "pause":  30, "spots": [{"spot": 6, "color":"blue"}, {"spot": 9, color:"red"}, {"spot": 0, color:"yellow"}, {"spot": 3, color:"green"}]},
		{ "pause":  30, "spots": [{"spot": 7, "color":"blue"}, {"spot":10, color:"red"}, {"spot": 1, color:"yellow"}, {"spot": 4, color:"green"}]},
		{ "pause":  30, "spots": [{"spot": 8, "color":"blue"}, {"spot":11, color:"red"}, {"spot": 2, color:"yellow"}, {"spot": 5, color:"green"}]},
		{ "pause":  20, "spots": [{"spot": 9, "color":"blue"}, {"spot": 0, color:"red"}, {"spot": 3, color:"yellow"}, {"spot": 6, color:"green"}]},
		{ "pause":  20, "spots": [{"spot":10, "color":"blue"}, {"spot": 1, color:"red"}, {"spot": 4, color:"yellow"}, {"spot": 7, color:"green"}]},
		{ "pause":  20, "spots": [{"spot":11, "color":"blue"}, {"spot": 2, color:"red"}, {"spot": 5, color:"yellow"}, {"spot": 8, color:"green"}]},

		// odds/evens
		{ "pause": 160, "spots": [{"spot":0, "color":"blue"}, {"spot":2, "color":"white"}, {"spot":4, "color":"blue"},
								 {"spot":6, "color":"white"}, {"spot":8, "color":"blue"}, {"spot":10, "color":"white"}]},
		{ "pause": 80, "spots": [{"spot":1, "color":"blue"}, {"spot":3, "color":"white"}, {"spot":5, "color":"blue"},
								 {"spot":7, "color":"white"}, {"spot":9, "color":"blue"}, {"spot":11, "color":"white"}]},
		{ "pause": 80, "spots": [{"spot":0, "color":"blue"}, {"spot":2, "color":"white"}, {"spot":4, "color":"blue"},
								 {"spot":6, "color":"white"}, {"spot":8, "color":"blue"}, {"spot":10, "color":"white"}]},
		{ "pause": 80, "spots": [{"spot":1, "color":"blue"}, {"spot":3, "color":"white"}, {"spot":5, "color":"blue"},
		                          {"spot":7, "color":"white"}, {"spot":9, "color":"blue"}, {"spot":11, "color":"white"}]},
                      
		// round
		{ "pause": 140, "spots":[{"spot":0, "color":"#ff0000", "velocity": 5}]},
		{ "pause":  20, "spots":[{"spot":1, "color":"#ff1a33", "velocity": 5}]}, 
		{ "pause":  20, "spots":[{"spot":2, "color":"#ff6000", "velocity": 5}]}, 
		{ "pause":  20, "spots":[{"spot":3, "color":"#ff9900", "velocity": 5}]},
		{ "pause":  20, "spots":[{"spot":4, "color":"#ffff00", "velocity": 5}]}, 
		{ "pause":  20, "spots":[{"spot":5, "color":"#66ff00", "velocity": 5}]}, 
		{ "pause":  20, "spots":[{"spot":6, "color":"#00ff1a", "velocity": 5}]},
		{ "pause":  20, "spots":[{"spot":7, "color":"#00ff99", "velocity": 5}]}, 
		{ "pause":  20, "spots":[{"spot":8, "color":"#0066ff", "velocity": 5}]}, 
		{ "pause":  20, "spots":[{"spot":9, "color":"#001aff", "velocity": 5}]},
		{ "pause":  20, "spots":[{"spot":10, "color":"#3300ff", "velocity": 5}]},		                 		 
		{ "pause":  20, "spots":[{"spot":11, "color":"#9900ff", "velocity": 5}]}, 

		// all
	{ "pause": 120, "spots":    [{"spot": 0, "color":"#ff0000", "velocity": 7}, {"spot": 1, "color":"#ff1a33", "velocity": 7}, {"spot": 2, "color":"#ff6000", "velocity": 7},
								 {"spot": 3, "color":"#ff9900", "velocity": 7}, {"spot": 4, "color":"#ffff00", "velocity": 7}, {"spot": 5, "color":"#66ff00", "velocity": 7},
								 {"spot": 6, "color":"#00ff1a", "velocity": 7}, {"spot": 7, "color":"#00ff99", "velocity": 7}, {"spot": 8, "color":"#0066ff", "velocity": 7},
								 {"spot": 9, "color":"#001aff", "velocity": 7}, {"spot":10, "color":"#3300ff", "velocity": 7}, {"spot":11, "color":"#9900ff", "velocity": 7}
	]},
	{ "pause": 120, "spots":    [{"spot": 6, "color":"#ff0000", "velocity": 8}, {"spot": 7, "color":"#ff1a33", "velocity": 8}, {"spot": 8, "color":"#ff6000", "velocity": 8},
								 {"spot": 9, "color":"#ff9900", "velocity": 8}, {"spot":10, "color":"#ffff00", "velocity": 8}, {"spot":11, "color":"#66ff00", "velocity": 8},
								 {"spot": 0, "color":"#00ff1a", "velocity": 8}, {"spot": 1, "color":"#00ff99", "velocity": 8}, {"spot": 2, "color":"#0066ff", "velocity": 8},
								 {"spot": 3, "color":"#001aff", "velocity": 8}, {"spot": 4, "color":"#3300ff", "velocity": 8}, {"spot": 5, "color":"#9900ff", "velocity": 8}
	]}
		
	]
};
/* */
/*
		aliceblue: 'f0f8ff',
        antiquewhite: 'faebd7',
        aqua: '00ffff',
        aquamarine: '7fffd4',
        azure: 'f0ffff',
        beige: 'f5f5dc',
        bisque: 'ffe4c4',
        black: '000000',
        blanchedalmond: 'ffebcd',
        blue: '0000ff',
        blueviolet: '8a2be2',
        brown: 'a52a2a',
        burlywood: 'deb887',
        cadetblue: '5f9ea0',
        chartreuse: '7fff00',
        chocolate: 'd2691e',
        coral: 'ff7f50',
        cornflowerblue: '6495ed',
        cornsilk: 'fff8dc',
        crimson: 'dc143c',
        cyan: '00ffff',
        darkblue: '00008b',
        darkcyan: '008b8b',
        darkgoldenrod: 'b8860b',
        darkgray: 'a9a9a9',
        darkgreen: '006400',
        darkkhaki: 'bdb76b',
        darkmagenta: '8b008b',
        darkolivegreen: '556b2f',
        darkorange: 'ff8c00',
        darkorchid: '9932cc',
        darkred: '8b0000',
        darksalmon: 'e9967a',
        darkseagreen: '8fbc8f',
        darkslateblue: '483d8b',
        darkslategray: '2f4f4f',
        darkturquoise: '00ced1',
        darkviolet: '9400d3',
        deeppink: 'ff1493',
        deepskyblue: '00bfff',
        dimgray: '696969',
        dodgerblue: '1e90ff',
        feldspar: 'd19275',
        firebrick: 'b22222',
        floralwhite: 'fffaf0',
        forestgreen: '228b22',
        fuchsia: 'ff00ff',
        gainsboro: 'dcdcdc',
        ghostwhite: 'f8f8ff',
        gold: 'ffd700',
        goldenrod: 'daa520',
        gray: '808080',
        green: '008000',
        greenyellow: 'adff2f',
        honeydew: 'f0fff0',
        hotpink: 'ff69b4',
        indianred : 'cd5c5c',
        indigo : '4b0082',
        ivory: 'fffff0',
        khaki: 'f0e68c',
        lavender: 'e6e6fa',
        lavenderblush: 'fff0f5',
        lawngreen: '7cfc00',
        lemonchiffon: 'fffacd',
        lightblue: 'add8e6',
        lightcoral: 'f08080',
        lightcyan: 'e0ffff',
        lightgoldenrodyellow: 'fafad2',
        lightgrey: 'd3d3d3',
        lightgreen: '90ee90',
        lightpink: 'ffb6c1',
        lightsalmon: 'ffa07a',
        lightseagreen: '20b2aa',
        lightskyblue: '87cefa',
        lightslateblue: '8470ff',
        lightslategray: '778899',
        lightsteelblue: 'b0c4de',
        lightyellow: 'ffffe0',
        lime: '00ff00',
        limegreen: '32cd32',
        linen: 'faf0e6',
        magenta: 'ff00ff',
        maroon: '800000',
        mediumaquamarine: '66cdaa',
        mediumblue: '0000cd',
        mediumorchid: 'ba55d3',
        mediumpurple: '9370d8',
        mediumseagreen: '3cb371',
        mediumslateblue: '7b68ee',
        mediumspringgreen: '00fa9a',
        mediumturquoise: '48d1cc',
        mediumvioletred: 'c71585',
        midnightblue: '191970',
        mintcream: 'f5fffa',
        mistyrose: 'ffe4e1',
        moccasin: 'ffe4b5',
        navajowhite: 'ffdead',
        navy: '000080',
        oldlace: 'fdf5e6',
        olive: '808000',
        olivedrab: '6b8e23',
        orange: 'ffa500',
        orangered: 'ff4500',
        orchid: 'da70d6',
        palegoldenrod: 'eee8aa',
        palegreen: '98fb98',
        paleturquoise: 'afeeee',
        palevioletred: 'd87093',
        papayawhip: 'ffefd5',
        peachpuff: 'ffdab9',
        peru: 'cd853f',
        pink: 'ffc0cb',
        plum: 'dda0dd',
        powderblue: 'b0e0e6',
        purple: '800080',
        red: 'ff0000',
        rosybrown: 'bc8f8f',
        royalblue: '4169e1',
        saddlebrown: '8b4513',
        salmon: 'fa8072',
        sandybrown: 'f4a460',
        seagreen: '2e8b57',
        seashell: 'fff5ee',
        sienna: 'a0522d',
        silver: 'c0c0c0',
        skyblue: '87ceeb',
        slateblue: '6a5acd',
        slategray: '708090',
        snow: 'fffafa',
        springgreen: '00ff7f',
        steelblue: '4682b4',
        tan: 'd2b48c',
        teal: '008080',
        thistle: 'd8bfd8',
        tomato: 'ff6347',
        turquoise: '40e0d0',
        violet: 'ee82ee',
        violetred: 'd02090',
        wheat: 'f5deb3',
        white: 'ffffff',
        whitesmoke: 'f5f5f5',
        yellow: 'ffff00',
        yellowgreen: '9acd32'
*/